import { z } from 'zod';

export const VoiceNoteSchema = z.object({
  id: z.string(),
  revision: z.number().int().nonnegative().default(0),
  duration: z.number(),
  transcription: z.string().nullable(),
  clientName: z.string(),
  contactId: z.string().nullable().optional(),
  contactName: z.string().optional(),
  meetingAt: z.string().datetime().nullable().optional(),
  meetingEndAt: z.string().datetime().nullable().optional(),
  crmActionCode: z.string().nullable().optional(),
  crmActionLabel: z.string().nullable().optional(),
  crmObjectiveCode: z.string().nullable().optional(),
  crmObjectiveLabel: z.string().nullable().optional(),
  crmObjectiveCodes: z.array(z.string()).optional(),
  crmObjectiveLabels: z.array(z.string()).optional(),
  productMentioned: z.string().optional(),
  nextAction: z.string().optional(),
  notes: z.string().optional(),
  companyId: z.string().nullable().optional(),
  relatedScanId: z.string().nullable().optional(),
  syncStatus: z.enum(['pending', 'synced', 'failed', 'deleted', 'syncing']).default('pending'),
  syncErrorCode: z.string().nullable().optional(),
  crmCommunicationId: z.string().nullable().optional(),
  crmSyncedRevision: z.number().int().nonnegative().nullable().optional(),
  crmUpdateAvailable: z.boolean().default(false),
  createdAt: z.string().datetime(),
});
export type VoiceNote = z.infer<typeof VoiceNoteSchema>;
