/**
 * Step 2 of the re-chunking workflow.
 *
 * Reads the headers generated by step 1 from `scripts/.cache/headers.json`,
 * prepends each header to its product's chunks, re-embeds the new text via
 * OpenAI text-embedding-3-large (dimensions: 1536, drop-in compatible with
 * the existing vector(1536) column), and updates the rows in Supabase.
 *
 * Safety:
 *   - Backs up the ORIGINAL chunk_text into metadata.original_text on first
 *     run, so rollback is just `chunk_text := metadata->>'original_text'`
 *     plus re-embedding with the old model.
 *   - --dry-run prints what it would do without writing to Supabase.
 *   - Idempotent: re-running with the same cache produces the same state.
 *
 * Run:
 *   cd apps/api && npx ts-node scripts/rechunk-step2-apply.ts --dry-run
 *   cd apps/api && npx ts-node scripts/rechunk-step2-apply.ts
 */

import * as dotenv from 'dotenv';
import * as path from 'path';
import * as fs from 'fs';

dotenv.config({ path: path.resolve(__dirname, '../.env') });

import OpenAI from 'openai';
import { createClient } from '@supabase/supabase-js';

const HEADERS_FILE = path.resolve(__dirname, '.cache/headers.json');

interface CachedHeader {
  header: string;
  generatedAt: string;
  productFamily: string;
  numChunks: number;
}

interface ChunkRow {
  id: string;
  product_name: string;
  chunk_text: string;
  metadata: Record<string, any>;
}

const SEPARATOR = '\n\n— Original datasheet —\n';

function buildNewChunkText(header: string, originalText: string): string {
  return `${header}${SEPARATOR}${originalText}`;
}

async function fetchAllChunks(supabase: any): Promise<ChunkRow[]> {
  const out: ChunkRow[] = [];
  let offset = 0;
  while (true) {
    const { data, error } = await supabase
      .from('product_chunks')
      .select('id, product_name, chunk_text, metadata')
      .range(offset, offset + 999);
    if (error) throw new Error(`Supabase fetch: ${error.message}`);
    if (!data || data.length === 0) break;
    out.push(...(data as any));
    if (data.length < 1000) break;
    offset += 1000;
  }
  return out;
}

async function generateEmbedding(openai: OpenAI, text: string): Promise<number[]> {
  const res = await openai.embeddings.create({
    model: 'text-embedding-3-large',
    input: text,
    dimensions: 1536,
  });
  return res.data[0].embedding;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const limitIdx = args.indexOf('--limit');
  const limit = limitIdx >= 0 ? parseInt(args[limitIdx + 1], 10) : Number.POSITIVE_INFINITY;

  if (!fs.existsSync(HEADERS_FILE)) {
    console.error(`Headers cache not found: ${HEADERS_FILE}\nRun step 1 first.`);
    process.exit(1);
  }
  const headers = JSON.parse(fs.readFileSync(HEADERS_FILE, 'utf8')) as Record<
    string,
    CachedHeader
  >;
  console.log(`Loaded ${Object.keys(headers).length} headers from cache.`);

  const supabase = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_ANON_KEY!,
  );
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY! });

  console.log('Fetching chunks from Supabase…');
  const chunks = await fetchAllChunks(supabase);
  console.log(`Found ${chunks.length} chunks.\n`);

  let processed = 0;
  let skippedNoHeader = 0;
  let skippedAlreadyApplied = 0;
  let failed = 0;
  const t0 = Date.now();

  for (const chunk of chunks) {
    if (processed >= limit) break;

    const cached = headers[chunk.product_name];
    if (!cached) {
      skippedNoHeader++;
      continue;
    }

    // Idempotency: if metadata.original_text exists, this chunk has already
    // been transformed in a prior run. Use original_text as the source.
    const originalText: string =
      chunk.metadata?.original_text ?? chunk.chunk_text;
    const alreadyApplied =
      typeof chunk.metadata?.original_text === 'string' &&
      chunk.chunk_text.startsWith(cached.header);

    if (alreadyApplied) {
      skippedAlreadyApplied++;
      continue;
    }

    const newChunkText = buildNewChunkText(cached.header, originalText);

    if (dryRun) {
      processed++;
      if (processed <= 3) {
        console.log(`\n[DRY] ${chunk.product_name} (${chunk.id})`);
        console.log(`  new text (${newChunkText.length} chars):`);
        console.log(`  ${newChunkText.slice(0, 250).replace(/\n/g, ' ')}…`);
      }
      continue;
    }

    try {
      const newEmbedding = await generateEmbedding(openai, newChunkText);
      const newMetadata = {
        ...(chunk.metadata ?? {}),
        original_text:
          chunk.metadata?.original_text ?? chunk.chunk_text,
        rechunk_version: 'v1-2026-05-11',
        embedding_model: 'text-embedding-3-large@1536',
      };
      const { error } = await supabase
        .from('product_chunks')
        .update({
          chunk_text: newChunkText,
          embedding: newEmbedding,
          metadata: newMetadata,
        })
        .eq('id', chunk.id);
      if (error) throw new Error(error.message);

      processed++;
      if (processed % 20 === 0) {
        const elapsed = ((Date.now() - t0) / 1000).toFixed(0);
        console.log(
          `[${processed + skippedAlreadyApplied + skippedNoHeader}/${chunks.length}] ${chunk.product_name} (${elapsed}s elapsed)`,
        );
      }
    } catch (err) {
      failed++;
      console.error(
        `✗ ${chunk.product_name} (${chunk.id}): ${(err as Error).message}`,
      );
    }
  }

  console.log(
    `\nDone. Updated: ${processed}, skipped (already applied): ${skippedAlreadyApplied}, skipped (no header): ${skippedNoHeader}, failed: ${failed}.`,
  );
  if (dryRun) {
    console.log('\n[DRY RUN] No writes were performed.');
  }
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
